### ISSUE TITLE
Regex instead of characters

### ISSUE THREAD

**Issue by pratham1002** [kdickerson/automatonSimulator#9]
Hey! I found this tool quite useful for creating DFAs in the browser, way better than drawing them on paper. But it would be much more useful if it could except regex instead of single character for transitions. Like the DFA I require (for a lexical analyzer) treats all digits the same, hence it would be nice to have regex like `[0-9]` or `[a-z|A-Z]` on the transition.

**Comment by kdickerson** [comment]
Thanks for your interest and the suggestion.  I'll have to think carefully about whether 1. this is feasible in the current design and 2.  I want to expand the project's scope to support it.

1. Currently transitions are just a lookup table. So they're really simple to set, change, apply, serialize, and deserialize.  Allowing character groups would require touching all of those areas across all 3 FSA types.  Implementing syntactic sugar for specifying multiple characters for the same transition would be a much simpler change than handling character ranges, but still touches all those areas.

2. I built this project as an educational tool for students learning about FSAs--specifically using the notation from Michael Sipser's "Introduction to the Theory of Computation".  Deviating from the syntax used in Sipser's book would reduce its educational value as students would need to reconcile the differences at a time when they're least capable of doing so (because they're still learning how these all work).

**Comment by kdickerson** [comment]
I've decided that I'm not going to implement character groups.  But do feel free to fork the project and implement it in your own branch.
